development:
  adapter: postgresql
  encoding: unicode
  database: todo_development
  pool: 5
  username: stevenweiss
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: todo_test
  pool: 5
  username: stevenweiss
  password:
